### ISSUE TITLE
Package causes SyntaxError: for including a "-" in the module's name

### ISSUE THREAD

**Issue by DonaldWolfson** [drakkar-lig/scamper-pywarts#1]
The README states the package is "warts" however, when I run ```pip list```, here is the package:

```Bash
$ pip list
scamper-pywarts (0.2.1)
```

So to import this package, the README should state:

```Python
import scamper-pywarts
from scamper-pywarts.traceroute import Traceroute
```

But when running this in my script I receive this SyntaxError,
```Bash
File "view-compressed-file.py", line 9
  import scamper-pywarts
                ^
SyntaxError: invalid syntax
```

Currently on Python3 incase that info is needed.

**Comment by jonglezb** [comment]
Hi,

The name in pypi is not necessarily the same as the Python module name. Lots of pypi packages have `-` in their names.

In this case, the README correctly states that you should use `import warts`.

Feel free to open a new ticket if something doesn't work as expected after that.

**Comment by DonaldWolfson** [comment]
When I run the code with"

```Python
import warts
from warts.traceroute import Traceroute
```

I get this output:

```Bash
Traceback (most recent call last):
  File "view-compressed-file.py", line 9, in <module>
    import warts
ModuleNotFoundError: No module named 'warts'
```

**Comment by jonglezb** [comment]
How did you install the package?

Make sure you installed the package for the version of python you are using (try `pip` / `pip2` / `pip3`)

**Comment by jonglezb** [comment]
You can try the `test.py` script, it expects a scamper file on stdin.

**Comment by DonaldWolfson** [comment]
Thanks! I was using pip instead of pip3, sorry for the hastle!

**Comment by jonglezb** [comment]
No worries, happy to help :)
